### ISSUE TITLE
Scraping frequency

### ISSUE THREAD

**Issue by wheatsnackbread** [ryanennns/LCBOstats#41]
Hey, love your work so far! Greatly appreciate you making LCBO data accessible by a great web API. 

Just curious, how frequently do you scrape the LCBO data? Some of the items are out of date.

Thanks,
wheatsnackbread

**Comment by ryanennns** [comment]
Hey! Can you point out a particular item and what about it is out of date? I run the update script every hour so it shouldn't leave anything behind. I'm curious what you've found out of sync / what caused it. Checking the server logs for the first time in a month or hasn't revealed anything too strange.
